name: Python Code Quality
on: [push]
jobs:
  lock_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.8"